FROM python:3.11 AS builder

WORKDIR /app

COPY requirements.txt .

RUN python -m venv /opt/venv

RUN /opt/venv/bin/pip install --no-cache-dir -r requirements.txt

FROM python:3.11-slim

WORKDIR /app

COPY --from=builder /opt/venv /opt/venv

COPY frontend/ ./frontend/
COPY backend/ ./backend/

EXPOSE 8501

ENV PATH="/opt/venv/bin:$PATH"

CMD ["streamlit", "run", "./main.py"]
